deployment:
  replicas: 1

config:
  greeting: 'Hello World.'

design: grpc
# must be one of: grpc, mqtt-producer, mqtt-processor, amqp, rust 

feature:
  # - servicemesh
  - observability
  # - observabilityClusterMonitoring

healthChecksDisabled: false