deployment:
  replicas: 1

config:
  greeting: 'Hello World.'

design: mqtt-producer
# must be one of: grpc, mqtt-producer, mqtt-processor, amqp, rust 

feature:
  # - servicemesh
  - observability
  # - observabilityClusterMonitoring

healthChecksDisabled: false

rhacsDisabled: false # set this to true if you do not have rhacs installed and did not run the RHACS-generate-ci-api-token.yaml in the root directory