{{- if eq .Values.design "mqtt-producer" }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "app.fullname" . }}-broker-info
stringData:
  amqp-host: ex-aao-amqp-acceptor-0-svc
  amqp-port: "5672"
{{- end }}