{{- if eq .Values.design "mqtt-producer" }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ coalesce .Values.amqBrokerInstanceNameOverride "ex-aao" }}-broker-info
stringData:
  amqp-host: {{ coalesce .Values.amqBrokerInstanceNameOverride "ex-aao" }}-amqp-acceptor-0-svc
  amqp-port: "5672"
  amqp-username: admin
  amqp-password: admin
{{- end }}