apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "app.fullname" . }}
spec:
  tags:
  - from:
      kind: DockerImage
      name: "{{ include "app.image" . }}:{{ .Chart.AppVersion }}"
    name: {{ .Chart.AppVersion }}