apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: octo-happiness-{{ .Values.design }}
  labels:
    {{- include "app.defaultLabels" . | indent 4 }}
spec:
  tags:
  - from:
      kind: DockerImage
      name: "{{ include "app.image" . }}:{{ .Chart.AppVersion }}"
    name: {{ .Chart.AppVersion }}