kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "app.fullname" . }}-maven-repo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
