apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "app.defaultLabels" . | indent 4 }}
    component: {{ include "app.fullname" . }}-service
  name: {{ include "app.fullname" . }}-service
spec:
  ports:
  - name: http-main
    port: 8080
    targetPort: http-main
  - name: https-main
    port: 8443
    targetPort: http-main
  {{- if eq .Values.design "mqtt-processor" }}
  - name: artemis
    port: 5672
    targetPort: artemis
  {{- else if eq .Values.design "grpc" }}
  - name: grpc
    port: 9000
    targetPort: grpc
  {{- end }}
  selector:
    {{- include "app.matchLabels" . | indent 4 }}
